#!/usr/bin/env node
import { Command } from 'commander'
import path from 'node:path'
import { runInterview } from './interview.js'
import { cloneTemplate } from './clone.js'
import { writeProfile } from './writeProfile.js'
import { verifyBuild } from './verifyBuild.js'
import { run } from './exec.js'

const DEFAULT_TEMPLATE = 'https://github.com/rishu1601/dev-portfolio-template.git'

const program = new Command()

program
  .name('create-dev-portfolio')
  .description('Clone dev-portfolio-template, answer a few questions, get a ready-to-run portfolio.')
  .argument('<directory>', 'directory to create the portfolio in')
  .option('--template <url>', 'template repo to clone', DEFAULT_TEMPLATE)
  .action(async (directory: string, options: { template: string }) => {
    const targetDir = path.resolve(process.cwd(), directory)

    try {
      const answers = await runInterview()

      cloneTemplate(options.template, targetDir)
      writeProfile(targetDir, answers)
      verifyBuild(targetDir)

      run('git', ['add', '.'], targetDir)
      run('git', ['commit', '-m', 'Initial portfolio generated by create-dev-portfolio'], targetDir)

      console.log(`\nYour portfolio is ready at ${targetDir}`)
      console.log('\nNext steps:')
      console.log(`  cd ${directory}`)
      console.log('  npm run dev        # preview locally at http://localhost:3000')
      console.log('  # edit config/profile.json to fill in experience, skills, and projects')
      console.log('  # push to GitHub and deploy to Vercel when ready\n')
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      console.error(`\ncreate-dev-portfolio failed: ${message}`)
      process.exitCode = 1
    }
  })

program.parse()
