#!/usr/bin/env node
import { Command } from 'commander'
import path from 'node:path'
import { runInterview } from './interview.js'
import { cloneTemplate } from './clone.js'
import { writeProfile } from './writeProfile.js'
import { verifyBuild } from './verifyBuild.js'
import { run } from './exec.js'
import { slugify } from './slugify.js'
import { maybeDeploy } from './deploy.js'

const DEFAULT_TEMPLATE = 'https://github.com/rishu1601/dev-portfolio-template.git'

// The interview only fills in personalInfo + githubUsername. experiences and
// projects get cleared to [] (writeProfile.ts) since the site hides those
// sections when empty — everything below still has the template's example
// content, because those sections always render regardless and would look
// broken (empty grids) if cleared instead.
const PLACEHOLDER_SECTIONS = [
  'skills',
  'education',
  'about (highlights, stats, core strengths paragraph)',
]

const program = new Command()

program
  .name('create-tech-dev-portfolio')
  .description('Clone dev-portfolio-template, answer a few questions, get a ready-to-run portfolio.')
  .argument('[directory]', 'directory to create the portfolio in (default: derived from your name)')
  .option('--template <url>', 'template repo to clone', DEFAULT_TEMPLATE)
  .action(async (directory: string | undefined, options: { template: string }) => {
    try {
      const answers = await runInterview()

      let dirName = directory
      if (!dirName) {
        dirName = `${slugify(answers.personalInfo.name)}-portfolio`
        console.log(`\nNo directory given — creating your portfolio in ./${dirName}`)
        console.log('(this name becomes your default Vercel project/domain later, so it is kept meaningful)')
      }
      const targetDir = path.resolve(process.cwd(), dirName)

      cloneTemplate(options.template, targetDir)
      writeProfile(targetDir, answers)
      verifyBuild(targetDir)

      run('git', ['add', '.'], targetDir)
      run('git', ['commit', '-m', 'Initial portfolio generated by create-dev-portfolio'], targetDir)

      console.log(`\n✓ Portfolio ready at ${targetDir}`)

      console.log('\nExperience and Projects start empty — they stay hidden on the site until')
      console.log('you add entries in config/profile.json.')

      console.log("\nHeads up — these sections still have the template's placeholder content:")
      for (const section of PLACEHOLDER_SECTIONS) {
        console.log(`  - ${section}`)
      }
      console.log('Edit them in config/profile.json before you publish this anywhere.\n')

      await maybeDeploy(targetDir, path.basename(targetDir))

      console.log('Starting the dev server (npm run dev) — http://localhost:3000, press Ctrl+C to stop...\n')
      run('npm', ['run', 'dev'], targetDir)
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err)
      console.error(`\ncreate-dev-portfolio failed: ${message}`)
      process.exitCode = 1
    }
  })

program.parse()
